packages:
  skyfan.tuya_fan: !include
    file: supplemental/tuya_fan.yaml
  skyfan.tuya_light: !include
    file: supplemental/tuya_light.yaml

substitutions:
  device_name: skyfandc
  device_friendly_name: skyfandc
  skyfan_model: "SKY1203"
  temp_name: ${device_friendly_name} Temperature
  light_name: ${device_friendly_name} Light
  fan_name: ${device_friendly_name} Fan
  uart_tx: uart_tx
  uart_rx: uart_rx

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  name_add_mac_suffix: false
  project:
    name: memphisraynz.skyfandc_esp32
    version: "0.9.5"

esp32:
  board: esp32-s3-devkitc-1

dashboard_import:
  package_import_url: github://memphisraynz/skyfandc/skyfan_micro_esp32.yaml@main

api:

# Disable logging
logger:
  baud_rate: 0

# i2c:
#   sda: 4
#   scl: 5
#   scan: true

ota:
  - platform: esphome  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .lan
    
# captive_portal:

tuya:
  id: tuyamcu

uart:
  tx_pin: ${uart_tx}
  rx_pin: ${uart_rx}
  baud_rate: 9600
  rx_full_threshold: 8

switch:
  - platform: gpio
    pin:
      number: 2
      inverted: true
    id: led
